_wandb:
    value:
        cli_version: 0.23.0
        e:
            vggsrqosmm0qy8qjzy5t0414kj1317h5:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                codePath: /Users/joyeechen/ResearchRepo/prototyping_scripts/Dec2prototypewithtogetheraicompute.ipynb
                codePathLocal: Dec2prototypewithtogetheraicompute.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "117833113600"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/ResearchRepo/.venv/bin/python
                git:
                    commit: 38b3ee034f3c8ea55404b9788b6c8cd5ed1a5ebd
                    remote: https://github.com/JoyeeChen/ResearchRepo.git
                host: Joyees-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/ResearchRepo/prototyping_scripts/Dec2prototypewithtogetheraicompute.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/ResearchRepo/prototyping_scripts
                startedAt: "2025-12-04T21:05:37.055974Z"
                writerId: vggsrqosmm0qy8qjzy5t0414kj1317h5
        m:
            - "1": accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples
              "6": []
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 49
                - 51
                - 95
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
                - 7
                - 14
                - 18
                - 62
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
weave_run_url:
    value: https://wandb.ai/chen-joyee-team/ResearchRepoPrototyping/r/call/019aeb2f-4d1d-733a-90bd-2cb539d64fdc
