_wandb:
    value:
        cli_version: 0.23.0
        e:
            y2u0j8lmjl0ivqvkwtveuonp24lt8zlj:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec24DimensionsRecommender.ipynb
                codePathLocal: Dec24DimensionsRecommender.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "122743029760"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/WelfareBenchmarkingRepo/.venv/bin/python
                git:
                    commit: 6c137c3cefe2dcd78410561480ab45eea8cef637
                    remote: https://github.com/JoyeeChen/WelfareBenchmarkingRepo.git
                host: Joyees-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec24DimensionsRecommender.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts
                startedAt: "2025-12-25T01:02:51.725991Z"
                writerId: y2u0j8lmjl0ivqvkwtveuonp24lt8zlj
        m:
            - "1": accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples
              "6": []
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 49
                - 51
                - 95
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
                - 7
                - 14
                - 18
                - 62
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
inspect task metadata:
    value:
        bxwMsCxwjGpRsXUZrG7D6V:
            weave_run_url: https://wandb.ai/chen-joyee-team/ResearchRepoPrototyping/r/call/019b5307-b145-7275-9768-457a0404eac9
