_wandb:
    value:
        cli_version: 0.23.1
        e:
            0tm28w54xubhcsag7sdriigqxr2779bl:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/DimensionsRecommenderDemo.ipynb
                codePathLocal: DimensionsRecommenderDemo.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "119406628864"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/WelfareBenchmarkingRepo/.venv/bin/python
                git:
                    commit: 7b1884cf5a34c09eaa16934a825b411c2b0bcdfa
                    remote: https://github.com/JoyeeChen/WelfareBenchmarkingRepo.git
                host: Joyees-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/DimensionsRecommenderDemo.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts
                startedAt: "2025-12-30T00:05:54.125795Z"
                writerId: 0tm28w54xubhcsag7sdriigqxr2779bl
        m:
            - "1": accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples
              "6": []
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 49
                - 51
                - 95
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
                - 7
                - 14
                - 18
                - 62
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-arm64
inspect task metadata:
    value:
        LHH64yWQEWDyu65cpjSEiv:
            weave_run_url: https://wandb.ai/chen-joyee-team/ResearchRepoPrototyping/r/call/019b6c93-566c-7de6-90ac-9b8d245c5121
