_wandb:
    value:
        cli_version: 0.23.0
        e:
            s2dxsbulkf1tc2zensgvlhwb81vasfzu:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec24DimensionsRecommender.ipynb
                codePathLocal: Dec24DimensionsRecommender.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "122739728384"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/WelfareBenchmarkingRepo/.venv/bin/python
                git:
                    commit: 6c137c3cefe2dcd78410561480ab45eea8cef637
                    remote: https://github.com/JoyeeChen/WelfareBenchmarkingRepo.git
                host: Joyees-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec24DimensionsRecommender.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts
                startedAt: "2025-12-25T00:57:07.271692Z"
                writerId: s2dxsbulkf1tc2zensgvlhwb81vasfzu
        m:
            - "1": accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples
              "6": []
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 49
                - 51
                - 95
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
                - 7
                - 14
                - 18
                - 62
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
inspect task metadata:
    value:
        HWLjttzrNYcXKhaFJ5dgBP:
            weave_run_url: https://wandb.ai/chen-joyee-team/ResearchRepoPrototyping/r/call/019b5302-6fc0-7f21-a647-9f463fa14ad9
