_wandb:
    value:
        cli_version: 0.23.0
        e:
            cg6f3atqsb6wfcfoqjqegurt86n9344v:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                codePath: /Users/joyeechen/ResearchRepo/welfare_defacc_prototyping_scripts/rrsInJupyterNotebooksDemo.ipynb
                codePathLocal: rrsInJupyterNotebooksDemo.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "120998481920"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/ResearchRepo/.venv/bin/python
                git:
                    commit: b33d39ab11f1d56641519d78cbb23a4bb7f0b65c
                    remote: https://github.com/JoyeeChen/ResearchRepo.git
                host: Joyees-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/ResearchRepo/welfare_defacc_prototyping_scripts/rrsInJupyterNotebooksDemo.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/ResearchRepo/welfare_defacc_prototyping_scripts
                startedAt: "2025-12-15T23:42:16.254910Z"
                writerId: cg6f3atqsb6wfcfoqjqegurt86n9344v
        m:
            - "1": accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples
              "6": []
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 49
                - 51
                - 95
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
                - 7
                - 14
                - 18
                - 62
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
weave_run_url:
    value: https://wandb.ai/chen-joyee-team/ResearchRepoPrototyping/r/call/019b2464-abac-7c35-9b4f-7374383ab8a8
