_wandb:
    value:
        cli_version: 0.23.0
        e:
            zfvdtq6233vwqd440e45hwf3l7mlm52k:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec15sampleEvalSet.ipynb
                codePathLocal: Dec15sampleEvalSet.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "119391690752"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/WelfareBenchmarkingRepo/.venv/bin/python
                git:
                    commit: 6c137c3cefe2dcd78410561480ab45eea8cef637
                    remote: https://github.com/JoyeeChen/WelfareBenchmarkingRepo.git
                host: Mac.localdomain
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec15sampleEvalSet.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts
                startedAt: "2025-12-24T18:00:12.425253Z"
                writerId: zfvdtq6233vwqd440e45hwf3l7mlm52k
        m: []
        python_version: 3.12.12
        t:
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
