_wandb:
    value:
        cli_version: 0.23.0
        e:
            cu9o2t55gsak1he5ou44n0uu1o8600yi:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "8589934592"
                codePath: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec15sampleEvalSet.ipynb
                codePathLocal: Dec15sampleEvalSet.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "124635144192"
                email: chen.joyee@gmail.com
                executable: /Users/joyeechen/WelfareBenchmarkingRepo/.venv/bin/python
                git:
                    commit: 6c137c3cefe2dcd78410561480ab45eea8cef637
                    remote: https://github.com/JoyeeChen/WelfareBenchmarkingRepo.git
                host: Joyees-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts/Dec15sampleEvalSet.ipynb
                python: CPython 3.12.12
                root: /Users/joyeechen/WelfareBenchmarkingRepo/prototyping_scripts
                startedAt: "2025-12-16T03:28:44.030318Z"
                writerId: cu9o2t55gsak1he5ou44n0uu1o8600yi
        m:
            - "1": accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples
              "6": []
              "7": []
        python_version: 3.12.12
        t:
            "1":
                - 49
                - 51
                - 95
            "2":
                - 49
                - 51
                - 95
            "3":
                - 2
                - 5
                - 7
                - 13
                - 14
                - 18
                - 62
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
weave_run_url:
    value: https://wandb.ai/chen-joyee-team/ResearchRepoPrototyping/r/call/019b2534-01fa-7c62-ac22-d968ea69447b
